### ISSUE TITLE
mongo-connector 2.5.0 no longer works with pymongo 3.0

### ISSUE THREAD

**Issue by rectalogic** [mongodb-labs/mongo-connector#619]
mongo-connector now assumes pymongo.__version__ exists but it doesn't in pymongo 3.0

```sh-session
$ virtualenv env
$ env/bin/pip install mongo-connector==2.5.0 pymongo==3.0
$ env/bin/mongo-connector
Logging to /tmp/mongo-connector.log.
Traceback (most recent call last):
  File "env/bin/mongo-connector", line 9, in <module>
    load_entry_point('mongo-connector==2.5.0', 'console_scripts', 'mongo-connector')()
  File "/tmp/env/local/lib/python2.7/site-packages/mongo_connector/util.py", line 94, in wrapped
    func(*args, **kwargs)
  File "/tmp/env/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1209, in main
    log_startup_info()
  File "/tmp/env/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1192, in log_startup_info
    LOG.always('pymongo version: %s', pymongo.__version__)
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by behackett** [comment]
I guess this is a bug, since __version__ was added in 2.9 and 3.1 (it does not exist on 3.0). I'd refer to jusr change mongo-connector to require 2.9 or >=3.1 rather than use "version". Is there a reason you need 3.0 exactly? Why not use the latest version of PyMongo (3.4)?

**Comment by rectalogic** [comment]
We had pymongo pinned at 3.0 and I upgraded only mongo-connector and noticed it failed to start. I'm going to upgrade our pymongo so it's ok with me if you bump the requirement.

**Comment by ShaneHarvey** [comment]
I think the simplest fix would be to check `hasattr(pymongo, '__version__')` or `hasattr(pymongo, 'version')`. There shouldn't be anything else that makes mongo-connector incompatible with  PyMongo 3.0. This way we can keep the pymongo>=2.9 requirement.
