### ISSUE TITLE
AttributeError: 'IndicesClient' object has no attribute 'delete_mapping'

### ISSUE THREAD

**Issue by jackbbhua** [mongodb-labs/mongo-connector#348]
Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 272, in run
    timestamp)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/doc_managers/elastic_doc_manager.py", line 111, in handle_command
    self.elastic.indices.delete_mapping(index=db.lower(),
AttributeError: 'IndicesClient' object has no attribute 'delete_mapping'

please have a check.thanks.

**Comment by llvtt** [comment]
mongo-connector currently only supports Elasticsearch 1.x. I'll have to look into how to support both ES 1.x and 2.x cleanly, since it looks like there may be some major differences between them.

The Python client library for Elasticsearch requires the version number of the client to match the server. Thus, mongo-connector requires the latest 1.x release of `elasticsearch-py`. I'll make the appropriate change in mongo-connector's setup.py. In the mean time, you can install version of the client library that works with mongo-connector (assuming you are running Elasticsearch 1.x as the server) with:

    pip install 'elasticsearch < 2.0'

**Comment by aherlihy** [comment]
Hello, support for Elastic 2.x is now live with Mongo-Connector 2.3.

In order to support Elastic 1.x and 2.x, the Elastic document manager has been pulled out of mongo-connector and is now located in a separate project.*

For more information on how to install and run the elastic doc managers, please see the Elastic doc manager documentation for the version of Elastic you prefer. These doc managers will only work with mongo-connector 2.3.0+.

Elastic 1.x doc manager: https://github.com/mongodb-labs/elastic-doc-manager

Elastic 2.x doc manager: https://github.com/mongodb-labs/elastic2-doc-manager

Hopefully this will solve your issue, but if not, feel free to reopen or file a new issue. Thank you!
